// Code generated by hertz generator.

package main

import (
	"auth/biz/config"
	"auth/biz/db"
	"auth/biz/middleware"
	"auth/biz/util/logger"
	_ "auth/docs"

	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/hertz-contrib/binding/go_playground"
	"github.com/hertz-contrib/swagger"
	swaggerFiles "github.com/swaggo/files"
)

// @title			AuthSystem
// @version		1.0
// @description	auth system
// @BasePath		/
// @schemes		http
func main() {
	logger.Init()
	config.Init("./conf/deploy.local.yml")
	db.Init()

	h := server.Default(
		server.WithHostPorts("0.0.0.0:8000"),
		server.WithCustomValidator(go_playground.NewValidator()),
	)
	h.Use(middleware.Suite()...)

	register(h)

	h.GET("/swagger/*any", swagger.WrapHandler(swaggerFiles.Handler))

	h.Spin()
}
